CREATE TABLE IF NOT EXISTS survey (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    age INTEGER,
    sex VARCHAR(10),
    region VARCHAR(100),
    contact_number VARCHAR(50),
    service_availed VARCHAR(200),
    client_type VARCHAR(100),
    cc1 VARCHAR(150),
    cc2 VARCHAR(150),
    cc3 VARCHAR(150),
    cc3_reason TEXT,
    sqd0 INTEGER,
    sqd1 INTEGER,
    sqd2 INTEGER,
    sqd3 INTEGER,
    sqd4 INTEGER,
    sqd5 INTEGER,
    sqd6 INTEGER,
    sqd7 INTEGER,
    sqd8 INTEGER,
    suggestions TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
